### ISSUE TITLE
Installing on el capitan

### ISSUE THREAD

**Issue by DorienD** [ywen/pivotal_to_pdf#24]
Hi!

I updated to el capitan and now creating current.pdf does not work anymore. I have tried reinstalling it but since el capitan you cant install in usr/bin anymore. I tried this:

```
sudo gem install pivotal_to_pdf -n/usr/local/bin
```

but now i get these errors:

```
Ignoring ffi-1.9.3 because its extensions are not built.  Try: gem pristine ffi-1.9.3
Ignoring json-1.8.1 because its extensions are not built.  Try: gem pristine json-1.8.1
16
>>> Generated PDF file in 'current.pdf'
[!] There was an error while generating the PDF file... What happened was:
/Library/Ruby/Gems/2.0.0/gems/prawn-0.12.0/lib/prawn/document.rb:372:in `initialize': Operation not permitted - current.pdf (Errno::EPERM)
    from /Library/Ruby/Gems/2.0.0/gems/prawn-0.12.0/lib/prawn/document.rb:372:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/prawn-0.12.0/lib/prawn/document.rb:372:in `render_file'
    from /Library/Ruby/Gems/2.0.0/gems/prawn-0.12.0/lib/prawn/document.rb:122:in `generate'
    from /Library/Ruby/Gems/2.0.0/gems/pivotal_to_pdf-formatters-0.1/lib/pivotal_to_pdf-formatters/default.rb:9:in `write_to'
    from /Library/Ruby/Gems/2.0.0/gems/pivotal_to_pdf-1.6.0/lib/pivotal_to_pdf.rb:26:in `current_iteration'
    from /Library/Ruby/Gems/2.0.0/gems/pivotal_to_pdf-1.6.0/bin/pivotal_to_pdf:16:in `current_iteration'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/pivotal_to_pdf-1.6.0/bin/pivotal_to_pdf:31:in `<top (required)>'
    from /usr/local/bin/pivotal_to_pdf:23:in `load'
    from /usr/local/bin/pivotal_to_pdf:23:in `<main>'
```

Has anyone else come across this problem?

**Comment by ywen** [comment]
Do you use rbenv or rvm? if so you can install it without need of sudo

If you haven't done so, install home-brew

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Then `brew install rbenv ruby-build`

Then `rbenv install 2.2.3`

Then `rbenv rehash`

To simplify things, restart your terminal app

then `which ruby` to ensure you use ruby from rbenv.

Then `gem install pivotal_to_pdf`

`rbenv rehash`

Should be good to go
